export default defineConfig({
    directories: {
        config: 'config',
        commands: 'commands',
        contracts: 'contracts',
        public: 'public',
        providers: 'providers',
        languageFiles: 'resources/lang',
        migrations: 'database/migrations',
        seeders: 'database/seeders',
        factories: 'database/factories',
        views: 'resources/views',
        start: 'start',
        tmp: 'tmp',
        tests: 'tests',
        httpControllers: 'app/controllers',
        models: 'app/models',
        services: 'app/services',
        exceptions: 'app/exceptions',
        mails: 'app/mails',
        middleware: 'app/middleware',
        policies: 'app/policies',
        validators: 'app/validators',
        events: 'app/events',
        listeners: 'app/listeners',
        stubs: 'stubs',
    },
})
